name: Use external Terraform module

on:
  workflow_dispatch:

jobs:# Allows GitHub to request the token that Azure needs
permissions:
  id-token: write
  contents: read

jobs:
  use-external-module:
    runs-on: ubuntu-latest
    environment: dev

    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v4

      - name: Azure login
        uses: azure/login@v3
        with: 
          tenant-id: ${{ vars.AZURE_TENANT_ID }}
          subscription-id: ${{ vars.AZURE_SUBSCRIPTION_ID }}
          auth-type: "IDENTITY"

      - name: Fetch IaC modules GH app private key
        id: fetch-iac-modules-app-pk
        run: |
          KEY=$(az keyvault secret show --name "iac-modules-app" --vault-name "KV-Canary-jgionet" --query "value" -o tsv)
          while IFS= read -r line; do
            if [ -n "$line" ]; then
              echo "::add-mask::$line"
            fi
          done <<< "$KEY"
          {
            echo 'private_key<<EOF'
            echo "$KEY"
            echo 'EOF'
          } >> "$GITHUB_OUTPUT"

      - name: Create IaC modules GH app token
        uses: actions/create-github-app-token@v3
        id: iac-modules-app-token
        with:
          client-id: ${{ vars.IAC_MODULES_CLIENT_ID }}
          private-key: ${{ steps.fetch-iac-modules-app-pk.outputs.private_key }}
          repositories: |
            iac-modules

      - name: Configure Git to access private IaC modules
        run: git config --global url."https://x-access-token:${{ steps.iac-modules-app-token.outputs.token }}@github.com/".insteadOf "https://github.com/"

      - name: Initialize Terraform
        id: terraform-init
        run: |
          terraform init

      - name: Generate Terraform plan
        id: terraform-plan
        run: |
          terraform plan -out=tfplan
          echo "tfplan_file=tfplan" >> "$GITHUB_OUTPUT"

      - name: Publish Terraform plan to step summary
        run: |
          echo '```hcl' >> "$GITHUB_STEP_SUMMARY"
          terraform show -no-color ${{ steps.terraform-plan.outputs.tfplan_file }} >> "$GITHUB_STEP_SUMMARY"
          echo '```' >> "$GITHUB_STEP_SUMMARY"

      - name: Apply Terraform plan
        id: terraform-apply
        run: |
          terraform apply -auto-approve ${{ steps.terraform-plan.outputs.tfplan_file }}
